name: Publish Latest

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Lint with shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"
      - name: Test with bash script
        run: |
          bash tests.sh
  push-dockerhub:
    needs: [test-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          export DOCKER_TAG="unfor19/bash-logging:latest"
          docker build . --file Dockerfile.example --tag "${DOCKER_TAG}"
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}"
