name: Update README.md
on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare tests.sh output
        run: |
          echo -e "\`\`\`\n$(tail -n +3 "logging.sh")\n\`\`\`" > "loggingsh.md"
      - uses: unfor19/replacer-action@master
        name: Update README.md file
        with:
          src-file-path: "loggingsh.md"
          dst-file-path: "README.md"
          start-value: "<!-- loggingsh_start -->"
          end-value: "<!-- loggingsh_end -->"
          git-user-name: "GitHub Actions"
          git-user-email: "githubactions@meirg.co.il"
          git-commit-msg: "Updated by GitHub Actions"
          git-skip-commit: false
          git-skip-push: false
          create-backup: true
