name: update-readme

on:
  push:
    branches: [master]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare tests.sh output
        run: |
          test_results="$(source tests.sh)"
          echo "${test_results}"
          echo -e "\`\`\`\n${test_results}\n\`\`\`" > ".testresults.log"
      - uses: unfor19/replacer-action@master
        name: Update README.md file with test results
        with:
          src-file-path: ".testresults.log"
          dst-file-path: "README.md"
          start-value: "<!-- replacer_start_tests -->"
          end-value: "<!-- replacer_end_tests -->"
