name: update-readme

on:
  push:
    branches: [master]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare tests.sh output
        run: |
          usage_file_path=.testresults.log
          test_results="$(source tests.sh)"
          echo -e "\`\`\`\n${test_results}\n\`\`\`" > "${usage_file_path}"
      - uses: unfor19/replacer-action@master
        name: Update README.md file with test results
        with:
          src-file-path: ".testresults.log"
          dst-file-path: "README.md"
          start-value: "<!-- tests_start -->"
          end-value: "<!-- tests_end -->"
